services:
  backend:
    container_name: h4g_backend
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - app.env
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
    networks:
      - h4g_deploy

  db:
    container_name: h4g_db
    image: postgres:14.6
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - h4g_deploy

volumes:
  caddy_data:
  caddy_config:
  pgdata:

networks:
  h4g_deploy:
    name: h4g_deploy
    external: true
