"""init

Revision ID: 37fc74e1b82f
Revises: 
Create Date: 2023-02-09 13:49:34.010750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37fc74e1b82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['credentials.email'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('talents',
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story', sa.String(), server_default='', nullable=False),
    sa.Column('job_types', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('job_modes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('job_title', sa.String(), server_default='', nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('availability', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('center_location', sa.String(), server_default='', nullable=False),
    sa.Column('weekly_hours', sa.Integer(), server_default='0', nullable=False),
    sa.Column('treatment_type', sa.String(), server_default='', nullable=False),
    sa.Column('photo_url', sa.String(), server_default='', nullable=False),
    sa.Column('is_displayed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('linkedin_url', sa.String(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['credentials.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('talent_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talents')
    op.drop_table('refresh_tokens')
    op.drop_table('credentials')
    # ### end Alembic commands ###
