"""update talent

Revision ID: d0d3bf22791b
Revises: d0910cffdbba
Create Date: 2023-02-10 12:49:42.709397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d3bf22791b'
down_revision = 'd0910cffdbba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talents', sa.Column('name', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talents', 'name')
    # ### end Alembic commands ###
